image: Visual Studio 2019

cache: C:\Tools\vcpkg\installed\

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - compiler: msvc
    - compiler: gcc

platform:
  - x86-windows

configuration:
  - Release

for:
  -
    matrix:
      only:
        - configuration: Release
          platform: x86-windows
          compiler: msvc
    before_build:
      - cd %APPVEYOR_BUILD_FOLDER%
      - mkdir build
      - cd build
    build_script:
      - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat"
      - cmake -G "NMake Makefiles" -DBUILD_STATIC=ON ..
      - nmake
      - if %ERRORLEVEL% GEQ 1 EXIT /B 1
  -
    matrix:
      only:
        - configuration: Release
          platform: x86-windows
          compiler: gcc
    environment:
      CHERE_INVOKING: yes
      MSYSTEM: MINGW32
    build_script:
      - cd %APPVEYOR_BUILD_FOLDER%
      - C:\msys64\usr\bin\bash -lc "./configure && make"

#install:
#  - cd C:\Tools\vcpkg
#  - if not exist downloads mkdir downloads
#  - cd downloads
#  - cd ..
#  - cd %APPVEYOR_BUILD_FOLDER%

